window.HWS_ARCHIVE_CONFIG = {
  navItems: [
    { section: "dashboard", icon: "layout-dashboard", label: "大屏首页", active: true },
    { section: "search", icon: "search", label: "智能检索" },
    { section: "keyword", icon: "building-2", label: "项目/组织/人员检索" },
    { section: "workType", icon: "files", label: "作品类型检索" },
    { section: "inbox", icon: "hard-drive", label: "资料入库" },
    { section: "media", icon: "play-square", label: "媒体中心" },
    { section: "finish", icon: "sparkles", label: "待收尾作品池" },
    { section: "authors", icon: "pen-tool", label: "作者中心" },
    { section: "ai", icon: "brain-circuit", label: "AI 知识库" },
    { section: "approval", icon: "shield-check", label: "审批权限" },
    { section: "backup", icon: "database-backup", label: "备份中心" },
  ],

  metrics: [
    { label: "文件总量", value: "9,482,311", note: "今日新增 18,426" },
    { label: "全文索引", value: "68%", note: "OCR 队列 12,304" },
    { label: "待收尾作品", value: "416", note: "S 级 38，A 级 122" },
    { label: "备份健康", value: "97%", note: "最近快照 05:30" },
  ],

  intakeSources: [
    {
      key: "mobile",
      icon: "smartphone",
      name: "手机",
      examples: "iPhone、安卓手机、微信/相册/文件App",
      access: "数据线、局域网投递、云端同步目录",
      target: "NAS 手机暂存区",
      status: "优先接入",
      risk: "中高",
      next: "先采集照片、视频、录音、聊天导出和文件夹",
    },
    {
      key: "tablet",
      icon: "tablet",
      name: "iPad/平板",
      examples: "iPad、安卓平板、手写稿、会议资料",
      access: "数据线、AirDrop、同步目录",
      target: "NAS 平板暂存区",
      status: "优先接入",
      risk: "中",
      next: "重点采集文档、图片、批注稿和会议资料",
    },
    {
      key: "old-computer",
      icon: "monitor",
      name: "旧电脑/不同主机",
      examples: "旧 Mac、Windows、服务器、员工电脑",
      access: "局域网共享、远程索引、移动硬盘中转",
      target: "NAS 主机暂存区",
      status: "分批接入",
      risk: "中",
      next: "先按电脑编号只读扫描，再汇总索引",
    },
    {
      key: "email",
      icon: "mail",
      name: "邮箱",
      examples: "企业邮箱、个人邮箱、历史客户邮件",
      access: "邮箱导出、EML/MSG、授权 API",
      target: "NAS 邮件暂存区",
      status: "待授权",
      risk: "高",
      next: "先导出邮件清单和附件索引，敏感邮件不进训练",
    },
    {
      key: "cloud",
      icon: "cloud",
      name: "云端云盘/公有云",
      examples: "iCloud、OneDrive、百度网盘、阿里云盘、对象存储",
      access: "同步目录、云端清单、API",
      target: "NAS 云盘暂存区",
      status: "清单优先",
      risk: "中高",
      next: "不全量下载，先清单对账和热数据同步",
    },
    {
      key: "nas",
      icon: "server",
      name: "NAS 总库",
      examples: "群晖、QNAP、TrueNAS、文件服务器",
      access: "SMB/AFP/NFS/API",
      target: "最终归总主库",
      status: "核心目标",
      risk: "中",
      next: "建立暂存区、正式库、快照区和禁训区",
    },
    {
      key: "usb",
      icon: "usb",
      name: "U盘/移动硬盘",
      examples: "客户拷贝盘、临时交接盘、移动 SSD",
      access: "本机挂载、只读扫描",
      target: "NAS 外接盘暂存区",
      status: "随到随扫",
      risk: "中高",
      next: "先查病毒和重复，再拷贝授权资料",
    },
    {
      key: "sd-card",
      icon: "sd-card",
      name: "SD卡/存储卡",
      examples: "相机卡、摄像机卡、录音笔卡",
      access: "读卡器、本机挂载",
      target: "NAS 素材暂存区",
      status: "优先保护",
      risk: "高",
      next: "先镜像备份，再抽帧、转写、人脸识别候选",
    },
    {
      key: "camera",
      icon: "camera",
      name: "相机/摄像机",
      examples: "单反、微单、运动相机、摄像机",
      access: "数据线、读卡器、采集站",
      target: "NAS 影像暂存区",
      status: "素材优先",
      risk: "中高",
      next: "采集照片、原片、成片、工程文件和拍摄日期",
    },
  ],

  intakeWorkflow: [
    { step: "01", title: "来源登记", detail: "记录手机、旧电脑、云盘、U盘、SD卡、相机等来源和负责人" },
    { step: "02", title: "只读采集", detail: "先做清单、路径、大小、修改时间，不擅自删除或改名" },
    { step: "03", title: "NAS 暂存", detail: "授权资料进入 NAS 暂存区，按来源分目录保留原貌" },
    { step: "04", title: "去重分类", detail: "按公司、项目、部门、作者、时间、格式、密级分层" },
    { step: "05", title: "AI 候选", detail: "低密级资料进入 OCR、转写、抽帧、人脸识别和案例库候选" },
  ],

  fieldSearches: [
    { field: "companyType", label: "公司类型", placeholder: "如：项目公司、集团公司" },
    { field: "project", label: "项目名称", placeholder: "如：汽车品牌发布会" },
    { field: "projectType", label: "项目类型", placeholder: "如：投标、年会、述职" },
    { field: "company", label: "公司名称", placeholder: "如：广告公司" },
    { field: "departmentSystem", label: "部门建制", placeholder: "如：集团法务、营销中心" },
    { field: "department", label: "部门名称", placeholder: "如：策划部" },
    { field: "employee", label: "员工姓名", placeholder: "作者/负责人/参与人" },
    { field: "functionRole", label: "人事/职能", placeholder: "如：文案、顾问、剪辑" },
    { field: "periodSearchText", label: "周期阶段", placeholder: "如：2016到2019、Q1、筹备期" },
    { field: "assetStage", label: "完整状态", placeholder: "残缺、完整、待补充" },
    { field: "qualityLevel", label: "作品等级", placeholder: "优质、经典案例、示范文档" },
    { field: "level", label: "密级", placeholder: "L0、L3、L6" },
    { field: "storageSourceType", label: "存储来源", placeholder: "本机、云盘、NAS、U盘" },
    { field: "storageProvider", label: "存储名称", placeholder: "iCloud、NAS、移动硬盘" },
    { field: "accessMode", label: "接入方式", placeholder: "本机直连、同步目录、SMB" },
    { field: "syncStrategy", label: "同步策略", placeholder: "云本同步、只读索引、三方校验" },
    { field: "syncStatus", label: "同步状态", placeholder: "已同步、待校验、离线" },
    { field: "crossCheckPolicy", label: "交叉校验", placeholder: "清单、大小、哈希、差异报告" },
    { field: "storageRisk", label: "存储风险", placeholder: "低、中、中高、高" },
    { field: "storageCostLevel", label: "成本等级", placeholder: "低、中、中高、高" },
  ],

  workTypes: [
    { key: "all", icon: "layers", label: "全部类型", active: true },
    { key: "image", icon: "image", label: "图片/照片" },
    { key: "video", icon: "video", label: "视频/影视" },
    { key: "audio", icon: "audio-lines", label: "录音/音乐" },
    { key: "email", icon: "mail", label: "邮件" },
    { key: "contract", icon: "file-signature", label: "合同" },
    { key: "proposal", icon: "clipboard-list", label: "方案/提案" },
    { key: "bid", icon: "briefcase-business", label: "标书/投标文件" },
    { key: "ppt", icon: "presentation", label: "PPT" },
    { key: "word", icon: "file-text", label: "Word/文档" },
    { key: "excel", icon: "table-2", label: "Excel/电子表格" },
    { key: "scan", icon: "scan-text", label: "扫描件" },
    { key: "logo", icon: "badge-check", label: "标识/LOGO" },
    { key: "design", icon: "palette", label: "画册/设计稿" },
    { key: "code", icon: "code-2", label: "程序/代码" },
    { key: "database", icon: "database", label: "数据库/数据表" },
    { key: "archive", icon: "package", label: "压缩包/备份包" },
  ],

  quickFilters: [
    { key: "all", label: "全部", active: true },
    { key: "finish", label: "待收尾" },
    { key: "classic", label: "经典案例" },
    { key: "audio", label: "录音转写" },
    { key: "video", label: "视频" },
    { key: "private", label: "高密级" },
  ],

  tableColumns: [
    { key: "title", label: "标题" },
    { key: "project", label: "项目名称" },
    { key: "projectType", label: "项目类型" },
    { key: "company", label: "公司" },
    { key: "companyType", label: "公司类型" },
    { key: "department", label: "部门" },
    { key: "author", label: "员工/作者" },
    { key: "owner", label: "负责人" },
    { key: "ownerLevel", label: "负责人等级" },
    { key: "functionRole", label: "职能" },
    { key: "period", label: "周期" },
    { key: "periodSearchText", label: "周期阶段" },
    { key: "workType", label: "作品类型" },
    { key: "assetStage", label: "完整状态" },
    { key: "qualityLevel", label: "作品等级" },
    { key: "format", label: "格式" },
    { key: "storageSourceType", label: "存储来源" },
    { key: "storageProvider", label: "存储名称" },
    { key: "accessMode", label: "接入方式" },
    { key: "syncStrategy", label: "同步策略" },
    { key: "syncStatus", label: "同步状态" },
    { key: "storageRisk", label: "存储风险" },
    { key: "storageCostLevel", label: "成本等级" },
    { key: "status", label: "状态" },
    { key: "score", label: "评分" },
    { key: "level", label: "密级" },
  ],

  appearance: {
    palettes: [
      {
        key: "jade",
        label: "墨绿",
        accent: "#12756f",
        accentSoft: "#e3f3f0",
        sidebar: "#12201a",
        sidebarActive: "#1b3329",
        page: "#f5f6f2",
      },
      {
        key: "ink",
        label: "黑金",
        accent: "#9a6a18",
        accentSoft: "#f4ead4",
        sidebar: "#171513",
        sidebarActive: "#2b251c",
        page: "#f7f5ef",
      },
      {
        key: "blue",
        label: "深蓝",
        accent: "#315f8c",
        accentSoft: "#e2edf7",
        sidebar: "#111d2d",
        sidebarActive: "#1a314d",
        page: "#f4f7fa",
      },
      {
        key: "wine",
        label: "酒红",
        accent: "#9b3f52",
        accentSoft: "#f6e2e6",
        sidebar: "#211319",
        sidebarActive: "#3a202a",
        page: "#f8f3f4",
      },
    ],
    fonts: [
      {
        key: "system",
        label: "系统默认",
        value: 'Inter, "PingFang SC", "Microsoft YaHei", "Noto Sans CJK SC", Arial, sans-serif',
      },
      {
        key: "pingfang",
        label: "苹方",
        value: '"PingFang SC", "Noto Sans CJK SC", Arial, sans-serif',
      },
      {
        key: "yahei",
        label: "微软雅黑",
        value: '"Microsoft YaHei", "Noto Sans CJK SC", Arial, sans-serif',
      },
      {
        key: "songti",
        label: "宋体",
        value: '"Songti SC", "SimSun", serif',
      },
      {
        key: "kaiti",
        label: "楷体",
        value: '"Kaiti SC", "KaiTi", serif',
      },
    ],
    fontSize: {
      default: 15,
      min: 13,
      max: 18,
    },
  },
};
