window.HWS_ARCHIVE_DATA = {
  archives: [
    {
      id: "HWS-ADV-2016-000123",
      title: "某汽车品牌发布会策划案",
      subtitle: "缺预算页、缺总结页，适合 AI 收尾",
      project: "某汽车品牌发布会",
      company: "广告公司",
      department: "策划部",
      author: "张三",
      owner: "李四",
      employees: ["张三", "李四", "活动执行组"],
      functionRole: "策划总监/项目负责人/活动执行",
      period: "2016-03 至 2016-06",
      workType: "方案/提案",
      format: "PPT",
      formatTags: ["proposal", "plan", "scheme", "ppt", "pptx"],
      type: "finish",
      status: "高价值半成品",
      completionScore: 82,
      qualityScore: 86,
      score: 86,
      grade: "A",
      level: "L2",
      preview: "video",
      summary:
        "该方案围绕汽车品牌发布会的开场视觉、传播节奏、现场动线和媒体邀约展开，现缺预算页和最终总结页，建议进入 AI 收尾池。",
    },
    {
      id: "HWS-MEDIA-2019-000456",
      title: "城市文化宣传片成片",
      subtitle: "视频、脚本、字幕、交付版完整",
      project: "城市文化宣传片",
      company: "传媒公司",
      department: "视频部",
      author: "王五",
      owner: "赵六",
      employees: ["王五", "赵六", "摄像组", "剪辑组"],
      functionRole: "导演/摄像/剪辑/后期",
      period: "2019-04 至 2019-05",
      workType: "视频/影视",
      format: "MP4",
      formatTags: ["video", "mp4", "mov", "subtitle"],
      type: "video",
      status: "经典作品",
      completionScore: 100,
      qualityScore: 93,
      score: 93,
      grade: "S",
      level: "L1",
      preview: "video",
      summary:
        "宣传片包含城市航拍、人物采访和片尾口号，可作为传媒公司视频风格库的代表样本。",
    },
    {
      id: "HWS-PR-2018-000782",
      title: "某客户危机沟通会议录音",
      subtitle: "已转写 83 分钟，待人工校对",
      project: "某客户危机公关沟通",
      company: "公关公司",
      department: "项目部",
      author: "会议录音",
      owner: "陈七",
      employees: ["陈七", "客户王总", "媒介经理"],
      functionRole: "公关顾问/媒介沟通/客户负责人",
      period: "2018-05-21",
      workType: "录音/会议转写",
      format: "M4A",
      formatTags: ["audio", "m4a", "mp3", "transcript"],
      type: "audio",
      status: "录音转写",
      completionScore: 83,
      qualityScore: 81,
      score: 81,
      grade: "A",
      level: "L3",
      preview: "audio",
      summary:
        "录音已完成说话人分离，摘要显示会议重点为媒体回应口径、客户补充材料和下一轮沟通时间。",
    },
    {
      id: "HWS-IMM-2020-001031",
      title: "欧洲移民客户申请材料",
      subtitle: "证件、合同、顾问方案，禁止训练",
      project: "欧洲移民客户申请",
      company: "移民公司",
      department: "顾问部",
      author: "顾问组",
      owner: "周八",
      employees: ["周八", "签证顾问", "客服专员"],
      functionRole: "移民顾问/签证顾问/客服/人事敏感资料",
      period: "2020-01 至 2020-09",
      workType: "合同/扫描件",
      format: "PDF",
      formatTags: ["contract", "scan", "pdf", "jpg"],
      type: "private",
      status: "客户隐私",
      completionScore: 96,
      qualityScore: 74,
      score: 74,
      grade: "B",
      level: "L4",
      preview: "doc",
      summary:
        "该档案涉及客户证件、签证材料和合同，仅允许授权人员受控检索，不进入 AI 训练库。",
    },
    {
      id: "HWS-CULTURE-2014-000624",
      title: "品牌故事长文初稿",
      subtitle: "4,820 字、36 段、7 个一级标题",
      project: "品牌故事内容工程",
      company: "文化传播公司",
      department: "文案部",
      author: "刘九",
      owner: "吴十",
      employees: ["刘九", "吴十", "编辑组"],
      functionRole: "文案作者/编辑/内容负责人",
      period: "2014-08 至 2014-09",
      workType: "Word/文章文档",
      format: "DOCX",
      formatTags: ["word", "doc", "docx", "article"],
      type: "finish",
      status: "初稿待收尾",
      completionScore: 92,
      qualityScore: 88,
      score: 88,
      grade: "A",
      level: "L1",
      preview: "doc",
      summary:
        "文章结构完整，缺少结尾落点和两个案例段落。系统已统计字数、段落、标题和作者风格特征。",
    },
    {
      id: "HWS-AD-2017-001208",
      title: "品牌视觉标识源文件",
      subtitle: "LOGO、VI、标准色、应用规范源文件",
      project: "品牌 VI 升级项目",
      company: "广告公司",
      department: "设计部",
      author: "设计组",
      owner: "孙一",
      employees: ["孙一", "设计组", "品牌顾问"],
      functionRole: "设计总监/品牌设计/视觉规范",
      period: "2017-07 至 2017-08",
      workType: "标识/LOGO",
      format: "AI/PSD/PNG",
      formatTags: ["logo", "vi", "ai", "psd", "png", "jpg", "design", "image"],
      type: "image",
      status: "品牌资产",
      completionScore: 100,
      qualityScore: 91,
      score: 91,
      grade: "S",
      level: "L1",
      preview: "image",
      summary:
        "包含品牌 LOGO 源文件、标准色、辅助图形和应用规范，适合进入品牌资产库和视觉风格库。",
    },
    {
      id: "HWS-TRADE-2021-001366",
      title: "供应商采购合同扫描件",
      subtitle: "合同、盖章页、报价附件、扫描归档",
      project: "年度供应商采购",
      company: "贸易公司",
      department: "采购部",
      author: "采购专员",
      owner: "钱二",
      employees: ["钱二", "采购专员", "法务审核"],
      functionRole: "采购/法务/合同管理",
      period: "2021-01 至 2021-12",
      workType: "合同/扫描件",
      format: "PDF/JPG",
      formatTags: ["contract", "scan", "pdf", "jpg", "supplier"],
      type: "private",
      status: "合同扫描件",
      completionScore: 98,
      qualityScore: 78,
      score: 78,
      grade: "B",
      level: "L3",
      preview: "doc",
      summary:
        "该档案为供应商年度采购合同和盖章扫描件，需要受控查看，可用于合同模板归类和供应商档案关联。",
    },
    {
      id: "HWS-FIN-2022-001520",
      title: "年度经营数据电子表格",
      subtitle: "收入、成本、项目利润、部门统计",
      project: "年度经营分析",
      company: "数据公司",
      department: "财务部",
      author: "财务组",
      owner: "郑三",
      employees: ["郑三", "财务组", "数据分析师"],
      functionRole: "财务/数据分析/经营统计",
      period: "2022-01 至 2022-12",
      workType: "Excel/电子表格",
      format: "XLSX/CSV",
      formatTags: ["excel", "xlsx", "xls", "csv", "spreadsheet", "table", "database"],
      type: "private",
      status: "财务敏感",
      completionScore: 97,
      qualityScore: 84,
      score: 84,
      grade: "A",
      level: "L4",
      preview: "doc",
      summary:
        "电子表格包含年度经营数据、项目利润和部门统计，只能在授权范围内分析，不进入通用 AI 训练库。",
    },
    {
      id: "HWS-PR-2018-001744",
      title: "客户往来邮件归档",
      subtitle: "邮件正文、附件、报价确认、媒体名单",
      project: "某客户媒体发布项目",
      company: "公关公司",
      department: "媒介部",
      author: "媒介经理",
      owner: "陈七",
      employees: ["陈七", "媒介经理", "客户联系人"],
      functionRole: "媒介/客户沟通/邮件归档",
      period: "2018-04 至 2018-06",
      workType: "邮件",
      format: "EML/MSG",
      formatTags: ["email", "eml", "msg", "mail", "attachment"],
      type: "private",
      status: "邮件归档",
      completionScore: 95,
      qualityScore: 80,
      score: 80,
      grade: "A",
      level: "L2",
      preview: "doc",
      summary:
        "邮件归档包含客户确认、媒体沟通和附件记录，可按联系人、项目、时间和附件类型检索。",
    },
    {
      id: "HWS-TECH-2023-001936",
      title: "客户管理系统代码备份包",
      subtitle: "源码、数据库脚本、部署说明、压缩备份",
      project: "客户管理系统",
      company: "科技公司",
      department: "技术部",
      author: "技术组",
      owner: "冯四",
      employees: ["冯四", "后端工程师", "运维工程师"],
      functionRole: "程序开发/数据库/运维部署",
      period: "2023-02 至 2023-09",
      workType: "程序/代码",
      format: "ZIP/SQL/JS",
      formatTags: ["code", "zip", "sql", "js", "database", "backup", "archive"],
      type: "private",
      status: "系统备份",
      completionScore: 90,
      qualityScore: 82,
      score: 82,
      grade: "A",
      level: "L5",
      preview: "doc",
      summary:
        "包含客户管理系统源码、数据库脚本和部署说明，属于核心技术资产，默认禁止外发和训练。",
    },
    {
      id: "HWS-SPORTS-2015-002108",
      title: "体育赛事运营服务投标文件",
      subtitle: "技术标、商务标、报价表、资质附件",
      project: "体育赛事运营服务投标",
      company: "体育公司",
      department: "项目部",
      author: "投标小组",
      owner: "高五",
      employees: ["高五", "投标专员", "财务报价", "法务审核"],
      functionRole: "投标/项目管理/商务报价/法务审核",
      period: "2015-09 至 2015-10",
      workType: "标书/投标文件",
      format: "PDF/DOCX/XLSX",
      formatTags: ["bid", "tender", "pdf", "docx", "xlsx", "quote"],
      type: "private",
      status: "投标归档",
      completionScore: 100,
      qualityScore: 87,
      score: 87,
      grade: "A",
      level: "L2",
      preview: "doc",
      summary:
        "该标书包含技术方案、商务报价、资质证明和投标附件，可作为体育项目投标模板和案例复盘资料。",
    },
  ],

  finishItems: [
    {
      title: "某汽车品牌发布会策划案",
      completionScore: 82,
      qualityScore: 86,
      score: 86,
      grade: "A",
      detail: "完成度 82%。缺预算页、结尾总结、执行时间表。建议 AI 先补结构，再由负责人确认。",
    },
    {
      title: "品牌故事长文初稿",
      completionScore: 92,
      qualityScore: 88,
      score: 88,
      grade: "A",
      detail: "4,820 字，36 段，标题 7 个。缺结尾和案例段落，可整理成公众号长文。",
    },
    {
      title: "孵化器招商路演 PPT",
      completionScore: 78,
      qualityScore: 92,
      score: 92,
      grade: "S",
      detail: "完成度 78%。缺财务模型和入驻企业案例，有机会成为经典招商模板。",
    },
  ],
};
